Document: seetaface-detector
Title: Debian seetaface-detector Manual
Author: <insert document author here>
Abstract: This manual describes what seetaface-detector is
 and how it can be used to
 manage online manuals on Debian systems.
Section: unknown

Format: debiandoc-sgml
Files: /usr/share/doc/seetaface-detector/seetaface-detector.sgml.gz

Format: postscript
Files: /usr/share/doc/seetaface-detector/seetaface-detector.ps.gz

Format: text
Files: /usr/share/doc/seetaface-detector/seetaface-detector.text.gz

Format: HTML
Index: /usr/share/doc/seetaface-detector/html/index.html
Files: /usr/share/doc/seetaface-detector/html/*.html
